<div class="row card">

    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="category-heading">
            <span style="font-weight: bolder;"><strong>TERMS & CONDITIONS</strong></span>

        </div>
    </div>


    <div class="row" style="padding: 40px;"> 

<p><strong>TERMS OF USE</strong></p>
<p>Digisteps Information Technology Solutions provides various features and tools that allow users to access obituaries, express condolences and share remembrances of friends and loved ones and meet an array of providers of required services/goods. These features and tools are availed at www.Buriani.co.ke (collectively the “Services”)
Please read the following Terms of Use before using the Services.
  
<p><strong>1. APPLICABILITY & ACCEPTANCE OF THESE TERMS OF USE</strong></p>

<p>By downloading, viewing, using, accessing, browsing, or submitting any content or material on or to the Services, you agree to these Terms of Use as a binding legal agreement between you and Buriani.co.ke without limitation or qualification. The term "you" or "You" shall refer to any person or entity who downloads, views, uses, accesses, browses or submits any content or material to the Services. If, however, you are accessing these Terms of Use from a website operated in conjunction with one of our affiliates (listed at http://Buriani.co.ke/about us/Affiliates, the terms of use of the Affiliate will govern unless such terms state otherwise.
The Services may contain a social networking and content using a third party(s) platform. You agree to be bound by these Terms of Use and the third party(s) Terms of Service. In addition, all rights and licenses you have granted to the third party(s) and all indemnities, duties, and obligations you owe to the third party(s) as expressed under the the third party(s) Terms of Service shall apply equally to Buriani.co.ke with respect to your use of the the third party(s) services and platform, as shall any limitations of liability and disclaimers of warranty. To the extent that there is a conflict between any provisions in these Terms of Use and the the third party(s) Terms of Service as to Buriani.co.ke, these Terms of Use will govern.
If you do not agree to these Terms of Use, then you may not use the Services. You agree that each time you access the Services, you shall be subject to the then-current Terms of Use, and continued use of the Services now or following modifications in these Terms of Use confirms that you have read, accepted, and agreed to be bound by such modifications.
<p><strong>2. USER LICENSE</strong></p>
<p>
a. Scope. Buriani.co.ke grants you permission (which may be revoked at any time for any reason or no reason) to view the Services and to download, integrate via authorized social media application, email, or print individual pages of the Services in accordance with these Terms of Use and solely for your own personal, non-commercial use, provided you do not remove any trademark, copyright or other notice contained on such pages. No other use is permitted. You may not, for example, incorporate the information, content, or other material from the Services in any database, compilation, archive or cache. You may not modify, copy, distribute, re-publish, transmit, display, perform, reproduce, publish, reuse, resell, license, create derivative works from, transfer, or sell any information, content, material, software, products or services obtained through the Services, except as specifically noted above.

Except as specifically authorized by Buriani.co.ke, you may not deep-link to the Services for any purpose or access the Services with any robot, spider, web crawler, extraction software, or any other automated process or device to scrape, copy, or monitor any portion of the Services or any information, content, or material from the Services. Buriani.co.ke reserves all of its statutory and common law rights against any person or entity who violates this paragraph. You may not link or frame to any pages of the Services or any content contained therein, whether in whole or in part, except as provided herein.
Any rights not expressly granted herein are reserved.<br>

b. User Conduct. You agree that your use of the Services is subject to all applicable laws and regulations. You also agree:<br>
i. to comply with applicable laws or rules regarding online conduct and acceptable Material, and regarding the transmission of technical data exported through the Services from Kenya or the country in which you reside;
<br>ii. not to host, submit content to or use the Services without the consent of a parent, guardian or educational supervisor if you are under the age of 18 (a "Minor");
<br>iii. not to use the Services for illegal purposes;
<br>iv. not to commit any acts of infringement on the Services or with respect to the Services content;
<br>v. not copy any content, including death notices, for republication in any other publication, whether in print or on-line;
<br>vi. not to create or maintain content in connection with the Services for or with any commercial or other purpose or intent that does not in good faith comport with the purpose or spirit of the Services, including but not limited to acquiring, designating, or choosing a website name or title, or website address or URL for resale or rental, depriving any family member or friend of a deceased person from establishing or using the Services in that person’s name, and linking to any commercial or other website from the Services;
<br>vii. not to attempt to gain unauthorized access to other computer systems from or through the Services;
<br>viii. not to interfere with another person’s use and enjoyment of the Services or another entity’s use and enjoyment of the Services;
<br>ix. not to use the Services for chain letters, junk mail, spamming, or use of distribution lists;
<br>x. not to upload or transmit viruses or other harmful, disruptive or destructive files;
<br>xi. not to disrupt, interfere with, or otherwise harm or violate the security of the Services, system resources, accounts, passwords, servers or networks connected to or accessible through the Services or affiliated or linked sites (including those of our Affiliates),


<p><strong>3. SERVICES CONTENT</strong></p>
<p>
a. Nature of User Material. Some features of the Services allow you and others to post, upload, transmit, display, publish, distribute, or otherwise submit material (collectively, "Submit"), including, but not limited to, images, information, articles, illustrations, lyrics, photos, audio files, poems, videos, or text (collectively, "Material"). You agree not to Submit any Material that:<br>
<br>i. contains vulgar, profane, abusive, hateful, or sexually explicit language, epithets or slurs, text or illustrations in poor taste, inflammatory attacks of a personal, sexual, racial or religious nature, or expressions of bigotry, racism, discrimination or hate;
<br>ii. is defamatory, threatening, disparaging, inflammatory, false, misleading, deceptive, fraudulent, inaccurate, or unfair, contains gross exaggeration or unsubstantiated claims, violates the privacy rights or right of publicity of any third party, is unreasonably harmful or offensive to any individual or community, contains any actionable statement, or tends to mislead or reflect unfairly on any other person, business or entity;
<br>iii. unfairly interferes with any third party’s uninterrupted use and enjoyment of the Services;
<br>iv. advertises, promotes or offers to trade any goods or services, except in areas specifically designated for such purpose;
<br>v. is intended primarily to promote a cause or movement, whether political, religious or other;
<br>vi. contains copyrighted content (copyrighted articles, illustrations, images, lyrics, photos, audio, video, poems, text, or other content) without the express permission of the owner of the copyrights in the content;
<br>vii. constitutes, promotes or encourages illegal acts, the violation of any right of any individual or entity, the violation of any local, state, national or international law, rule, guideline or regulation, or otherwise creates liability;
<br>viii. discloses any personal identifying information relating to or images of a Minor without consent of a parent, guardian or educational supervisor;
<br>ix. infringes any copyright, trademark, patent, trade secret, or other intellectual property right;
<br>x. contains viruses or other harmful, disruptive or destructive files;
<br>xi. harms or is inappropriate for minors to view;
<br>xii. links to any commercial or other website;
<br>xiii. is not otherwise in compliance with these Terms of Use.
<br>
b. User Representations and Warranties. Each time you Submit Material to the Services, you represent and warrant that you have the right to Submit the Material, which means:<br>
<br>i. you are the author of the Material, or
<br>ii. the Material is not protected by copyright law, or
<br>iii. you have express permission from the copyright owner to post the Material to the Services ; and
<br>iv. you have the right to grant Buriani.co.ke the license set out in these Terms of Use; and
<br>
v. the Material you Submit does not violate these Terms of Use.
<br>

c. User License Grant to Buriani.co.ke You grant Buriani.co.ke, its affiliates  and related entities a royalty-free, perpetual, irrevocable, non-exclusive right and license to use, copy, modify, display, archive, store, publish, transmit, perform, distribute, reproduce and create derivative works from all Material you provide to Buriani.co.ke any form, media, software or technology of any kind now existing or developed in the future. Without limiting the generality of the previous sentence, you authorize Buriani.co.ke to include the Material you provide in a searchable format that may be accessed by users of the Services and other websites. You also grant Buriani.co.ke and its affiliates and related entities the right to use your name and any other information about you that you provide in connection with the use, reproduction or distribution of such Material. You also grant buriani.co.ke the right to use the Material and any facts, ideas, concepts, know-how or techniques ("Information") contained in any Material or communication you send to us for any purpose whatsoever, including but not limited to, developing, manufacturing, promoting and/or marketing products and services. You grant all rights described in this paragraph in consideration of your use of the Services without the need for additional compensation of any sort to you. Buriani.co.ke does not claim ownership of Material you Submit to the Services.
<br>
<br>
d. Disclaimer of Responsibility for Material. You acknowledge and agree that Buriani.co.ke does not control user-generated content or Material Submitted to the Services, and disclaims any responsibility for such Material. Buriani.co.ke specifically disclaims any duty, obligation, or responsibility, to review, screen, refuse to post, remove, or edit any such content, or other Material. In addition, Buriani.co.ke does not represent or warrant that any other content or information accessible via the Services is accurate, complete, or current. Price and availability of information is subject to change without notice. Buriani.co.ke assumes no responsibility or liability for any errors or omissions in the content of the Services.

<br>
<br>e. Review & Removal of Material.
<br>i. Buriani.co.ke reserves the right (but disclaims any duty, obligation, or responsibility) to review, screen, refuse to post, remove in their entirety, or edit (at any time and without prior notice) any content or any Material available through the Services that Buriani.co.ke believes, in its absolute and sole discretion, may violate Sections 2(b), 3(a), or 3(b) above. Buriani.co.ke also reserves the right (but disclaims any duty, obligation, or responsibility) to refuse to post, remove in their entirety, or edit (at any time and without prior notice) any content or Material available through or Submitted to the Services for any reason or no reason whatsoever, in its absolute and sole discretion. In cases in which payment has been made in connection with Services content that has been removed for reasons other than a breach of 2(b), 3(a) or 3(b) above, Buriani.co.ke will issue a refund.
<br>ii. If you believe in good faith that content or Material hosted by the Services infringes your copyright, you (or your agent) may send Buriani.co.ke a notice requesting that the content or Material be removed, or access to it blocked. The notice must include the following information: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed (or if multiple copyrighted works are covered by a single notification, a representative list of such works); (c) identification of the material that is claimed to be infringing or the subject of infringing activity, and information reasonably sufficient to allow Buriani.co.ke to locate the content or Material within the Services; (d) the name, address, telephone number and email address (if available) of the complaining party; (e) a statement that the complaining party has a good faith belief that use of the content or Material in the manner complained of is not authorized by the copyright owner, its agent or the law; and (f) a statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, send us a counter-notice. Notices and counter-notices must meet the then-current statutory requirements. Notices and counter-notices with respect to the Service should be sent to info@buriani.co.ke or Digisteps Information Technology Solutions, Postal 14674-00100 NAIROBI, BuruBuru, Mumias South Rd. Epren Centre 3rd Floor Suite 24. Be aware that there can be penalties for false claims. We reserve the right to terminate the account of any user who is a copyright infringer.
<br><br>
f. Proprietary Rights. You acknowledge and agree that the Services contain proprietary information and content that is protected by intellectual property and other laws, and may not be used except as provided in these Terms of Use without advance, written permission of Buriani.co.ke. All designs, text, graphics, interfaces, and images (and the selection and arrangements thereof), and software, hypertext markup language ("HTML"), scripts, active server pages, and other content and software used in the Services are ©2017 Digisteps Information Technology  Solutions., all rights reserved.

<p><strong>4. TERMINATION AND MODIFICATIONS TO THE SERVICES</strong></p>
<p>Digisteps IT Solutions reserves the right, in its sole and absolute discretion, to modify, suspend, or discontinue at any time, with or without notice, the Services (or any part thereof), including but not limited to the Services’ features, functions, look and feel.
<p><strong>5. INDEMNITY</strong></p>
<p>You agree to indemnify and hold Buriani.co.ke,  its parents, subsidiaries and affiliates,  agents, officers, directors, or other employees harmless from any claim, demand, or damage (whether direct, indirect, or consequential, including reasonable attorneys’ fees, made by anyone in connection with your use of the Services, with Material or Information you Submit on or through the Services, with any alleged infringement of intellectual property or other right of any person or entity relating to the Services, your violation of these Terms of Use, and any other acts or omissions relating to the Services.
<p><strong>6. DISCLAIMER OF WARRANTIES</strong></p>
<p>THE INFORMATION, CONTENT, PRODUCTS, SERVICES, AND MATERIALS PROVIDED BY THE SERVICES (WHETHER PROVIDED BY BURIANI.CO.KE,  YOU, OTHER USERS, AFFILIATES OR THIRD PARTIES), INCLUDING WITHOUT LIMITATION, MATERIAL, TEXT, PHOTOS, GRAPHICS, AUDIO FILES, VIDEO, AND LINKS, ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
TO THE MAXIMUM EXTENT PERMITTED BY LAW, BURIANI.CO.KE DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NONINFRINGEMENT, FREEDOM FROM COMPUTER VIRUS, AND IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING OR COURSE OF PERFORMANCE.
<p><strong>7. LIMITATION OF LIABILITY</strong></p>
<p>
a. IN NO EVENT SHALL BURIANI.CO.KE  LIABLE TO YOU FOR ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, OR ANY LOSS OR DAMAGES WHATSOEVER (EVEN IF BURIANI.CO.KE HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER IN AN ACTION UNDER CONTRACT, NEGLIGENCE, OR ANY OTHER THEORY, IN ANY MANNER ARISING OUT OF OR IN CONNECTION WITH THE USE, INABILITY TO USE OR PERFORMANCE OF THE SERVICES. BURIANI.CO.KE ASSUMES NO RESPONSIBILITY AND SHALL NOT BE LIABLE FOR ANY DAMAGES TO, OR VIRUSES THAT MAY INFECT, YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS TO, USE OF, BROWSING OF, OR DOWNLOADING OF ANY MATERIAL FROM THE SERVICES. BURIANI.CO.KE ASSUMES NO RESPONSIBILITY OR LIABILITY IN ANY MANNER ARISING OUT OF OR IN CONNECTION WITH ANY INFORMATION, CONTENT, PRODUCTS, OR MATERIAL AVAILABLE ON OR THROUGH THE SERVICES, AS WELL AS ANY THIRD PARTY WEBSITE PAGES OR ADDITIONAL WEBSITES LINKED TO THE SERVICES, FOR ANY ERROR, DEFAMATION, LIBEL, SLANDER, OMISSION, FALSEHOOD, OBSCENITY, PORNOGRAPHY, PROFANITY, DANGER, OR INACCURACY CONTAINED THEREIN. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN NO EVENT SHALL BURIANI.CO.KE, TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, EXCEED THE AMOUNT PAID BY YOU TO DIGISTEPS IT SOLUTIONS OR AN AFFILIATE, IF ANY.
b. YOU AND BURIANI.CO.KE AGREE THAT THE WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY IN THESE TERMS OF USE ARE MATERIAL, BARGAINED-FOR BASES OF THIS AGREEMENT, AND THAT THEY HAVE BEEN TAKEN INTO ACCOUNT IN DETERMINING THE CONSIDERATION TO BE GIVEN BY EACH PARTY UNDER THIS AGREEMENT AND IN THE DECISION BY EACH PARTY TO ENTER INTO THIS AGREEMENT. YOU AND BURIANI.CO.KE AGREE THAT THE WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY IN THESE TERMS OF USE ARE FAIR AND REASONABLE.
c. IF YOU ARE DISSATISFIED WITH THE SERVICES OR DO NOT AGREE TO ANY PROVISIONS OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SERVICES, EXCEPT AS MAY BE PROVIDED FOR IN SECTION 7(a) ABOVE.

<p><strong>8. CANCELLATION, TERMINATION, TRANSFER, AND EXPIRATION OF ACCOUNT OR SERVICES</strong></p>
<p>
a. You may cancel or terminate your password, account and/or use of the Services, with or without cause at any time, upon providing written notice to Buriani.co.ke If you cancel or terminate your account or any Services or upon expiration of your account or service, your cancellation/termination/expiration will take effect immediately. Upon termination, your right to use your account or subject Services immediately ceases. Your notice to Buriani.co.ke of cancellation or termination must be sent via email or conventional mail as set forth in these Terms of Use.
b. Buriani.co.ke, in its sole and absolute discretion, and at any time and with or without prior notice to you. may suspend, cancel, transfer, or terminate your password, account, any site within an account and/or use of any Services for any reason whatsoever (including and without limitation, due to lack of use, commercial use, cybersquatting, Buriani.co.ke  resolution of any dispute among multiple persons claiming the right to use the same or similar accounts or services, or Buriani.co.ke’s belief, in its absolute and sole discretion, that you have violated or acted inconsistently with the letter or spirit of these Terms of Use). In the event of a dispute or conflict among, or complaint from, users of the Services about another’s right to establish, use, or maintain an account or Services, Buriani.co.ke reserves for itself the sole right to determine whether or how to resolve such dispute, conflict or complaint, with or without factual or other investigation.
c. Upon expiration, or cancellation or termination by either party, of your account, your password, and/or use of any Services, you will have no right to any Material or Information you Submitted, and Buriani.co.ke may temporarily or permanently block access to, remove, deactivate, delete, and discard all such Material or Information. Buriani.co.ke accepts no liability for removed or deleted Material or Information. In addition, any contracts (verbal, written, or assumed) with respect to your account, Material or Information you Submit, and/or use of any Services, will be terminated at Buriani.co.ke’s discretion. You agree that Buriani.co.ke will not be liable to you or any third-party for any termination of your access to any Services.
d. Upon suspension, cancellation, or termination of your account or your use of any Service (for whatever reason), there shall be no refund of money you paid to Digisteps IT Solutions

<p><strong>9. PERMANENCE OF MATERIAL</strong></p>
<p>
Subject to its suspension, cancellation, and termination rights and rights to remove Material, Buriani.co.ke represents that the Services content sponsored as "permanent" will remain available through the Services for the duration of Buriani.co.ke, Inc.’s existence, and that each Guest Book sponsored as "one year" will remain available through the Services for one year from the date of sponsorship, unless: (a) the Services ceases to exist in whole or in part during the relevant period; or (b) acts or events beyond the reasonable control of Buriani.co.ke cause a deletion, loss of data, failure to store, or other interruption in or termination of the availability of the Services content that you sponsored, or any other service to which you subscribed. You may at any time ask Buriani.co.ke to delete without charge the Services content, or other service that you sponsored or purchased.
<p><strong>10. MINORS</strong></p>
<p>
The consent of a parent, guardian or educational supervisor shall be required before a Minor can use the Services. Use of the Services is confirmation that the person is an adult or a Minor who has received permission from a parent, guardian or educational supervisor to use the Services. A parent, guardian or educational supervisor will be responsible for any activities of a Minor in connection with the Services regardless of whether the Minor has received permission from the parent, guardian or educational supervisor to use the Services.
Pursuant to relevant laws, Buriani.co.ke notifies You that parental control protection (such as computer hardware, software or filtering services) are commercially available that may assist You in limiting material that is harmful to Minors.
 
<p><strong>11. YOUR ACCOUNT, PASSWORD, AND SECURITY</strong><br>
<br>a. Some features of the Services may require you to register and/or create an account with Buriani.co.ke During this process, you must select an account designation and password and provide certain personal information to Buriani.co.ke, including a valid email address. In consideration of the use of Buriani.co.ke Services, you agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the registration form, and (b) maintain and promptly update the personal information you provide to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or Buriani.co.ke has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Buriani.co.ke has the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).
<br>b. You are responsible for maintaining the confidentiality and security of your account and password, and you are fully responsible for all activities that occur under your password or account, and for any other actions taken in connection with the account or password. You agree to (a) immediately notify Buriani.co.ke of any known or suspected unauthorized use(s) of your password or account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of your password or credit card information; and (b) ensure that you exit from your account at the end of each session. Buriani.co.ke will not be liable for any injury, loss or damage of any kind arising from or relating to your failure to comply with (a) and (b) or for any acts or omissions by you or someone else using your account and/or password.
</p>
<p><strong>12. LINKS AND FARMING</strong></p>
<p>
As a courtesy to you, the Services may offer links to other websites. Some of these websites may be affiliated with Buriani.co.ke while others are not. Buriani.co.ke is not responsible for the contents of any website pages created and maintained by organizations independent of Digisteps IT Solutions. Visiting any such third-party website pages is at your own risk. Digisteps IT Solutions has no control of these third-party website pages, nor can it guarantee the accuracy, completeness, or timeliness of information in third-party website pages. Your use of such information is voluntary, and your reliance on such information should be made only after independent review. References to commercial products or services within any such third-party website pages do not constitute or imply an endorsement by Digisteps IT Solutions By using the Services, you acknowledge that Digisteps IT Solutionsis responsible neither for the availability of, nor the content located on or through any third-party website pages.

<p><strong>13. CONSIDERATION</strong><br>
You acknowledge that these Terms of Use are supported by reasonable and valuable consideration, the receipt and adequacy of which are hereby acknowledged. Without limiting the foregoing, you acknowledge that such consideration includes, without limitation, your use of the Services and receipt or use of data, content, products, services, Material and Information available at or through the Services, the possibility of our review, use or display of your user-generated content, and the possibility of publicity and promotion from our review, use or display of your user-generated content.
</p>
<p><strong>14. GENERAL</strong><br>
<br>a. Enforceability. If any portion of these Terms of Use is found to be void, invalid or otherwise unenforceable, then that portion shall be deemed to be superseded by a valid, enforceable provision that matches the intent of the original provision as closely as possible. The remainder of these Terms of Use shall continue to be enforceable and valid according to terms contained herein.<br>
<br>b. Entire Agreement. Except as expressly provided in a particular "Legal Notice" or other notice on particular pages of the Services, these Terms of Use, which hereby incorporate by reference the terms of Buriani.co.ke, constitute the entire agreement between you and Buriani.co.ke superseding all prior agreements regarding the Services.<br>
<br>c. No Waiver. The failure of Buriani.co.ke to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of said right or provision. Neither party hereto shall be deemed to be in default of any provision of the Terms of Use or for failure in performance resulting from acts or events beyond the reasonable control of such party and arising without its fault or negligence, including, but not be limited to, acts of God, civil or military authority, interruption of electric or telecommunication services, civil disturbances, acts of war or terrorists, strikes, fires, floods or other catastrophes.<br>
<br>d. Headings & Construction. The section titles in the Terms of Use are for your convenience only and carry no contractual or legal effect whatsoever. The language in these Terms of Use shall be interpreted in accordance with its fair meaning and shall not be strictly interpreted for or against either party.
<br>e. Contact info@Buriani.co.ke. For purposes of providing notice of cancellation or termination, contact Digisteps Information Technology Solutions, Postal 14674-00100 NAIROBI, BuruBuru, Mumias South Rd. Epren Centre 3rd Floor Suite 24.
</p>


    </div>
</div>